name: USA Stock Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python usa_stock.py
